name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - github_actions

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: github_actions
      - name: Create cluster
        uses: denniskpw/doks-actions/create-cluster@master
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DigitalOceanToken }}
      - uses: ./.github/actions/check-kubeconfig
      - name: Delete cluster
        if: always()
        uses: denniskpw/doks-actions/delete-cluster@master
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DigitalOceanToken }}
        with:
          CLUSTER_ID: ${{ steps.cluster.outputs.CLUSTER_ID }}
